/*
* Sketch generated by duck2spark from Marcus Mengs aka MaMe82
*
*/
#include "DigiKeyboard.h"

#define DUCK_LEN 376
const PROGMEM uint8_t duckraw [DUCK_LEN] = {
	0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 215, 41, 0, 21, 8, 0, 255, 0, 145, 19, 0, 18, 0, 26, 0, 8, 0, 21, 0, 22, 0, 11, 0, 8, 0, 15, 0, 15, 0, 44, 0, 45, 0, 8, 0, 19, 0, 44, 0, 5, 0, 28, 0, 19, 0, 4, 0, 22, 0, 22, 0, 0, 200, 40, 0, 0, 200, 19, 0, 18, 0, 26, 0, 8, 0, 21, 0, 22, 0, 11, 0, 8, 0, 15, 0, 15, 0, 44, 0, 38, 2, 17, 0, 8, 0, 26, 0, 45, 0, 18, 0, 5, 0, 13, 0, 8, 0, 6, 0, 23, 0, 44, 0, 22, 2, 28, 0, 22, 0, 23, 0, 8, 0, 16, 0, 55, 0, 17, 2, 8, 0, 23, 0, 55, 0, 26, 2, 8, 0, 5, 0, 6, 2, 15, 0, 12, 0, 8, 0, 17, 0, 23, 0, 39, 2, 55, 0, 7, 2, 18, 0, 26, 0, 17, 0, 15, 0, 18, 0, 4, 0, 7, 0, 9, 2, 12, 0, 15, 0, 8, 0, 38, 2, 52, 0, 11, 0, 23, 0, 23, 0, 19, 0, 51, 2, 56, 0, 56, 0, 26, 0, 26, 0, 26, 0, 55, 0, 12, 0, 11, 0, 4, 0, 6, 0, 14, 0, 55, 0, 8, 0, 24, 0, 56, 0, 9, 0, 12, 0, 15, 0, 8, 0, 22, 0, 56, 0, 24, 2, 4, 2, 6, 2, 55, 0, 19, 0, 22, 0, 30, 0, 52, 0, 54, 0, 52, 0, 24, 2, 4, 2, 6, 2, 55, 0, 19, 0, 22, 0, 30, 0, 52, 0, 39, 2, 0, 200, 40, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 215, 19, 0, 18, 0, 26, 0, 8, 0, 21, 0, 22, 0, 11, 0, 8, 0, 15, 0, 15, 0, 44, 0, 55, 0, 100, 0, 24, 2, 4, 2, 6, 2, 55, 0, 19, 0, 22, 0, 30, 0, 0, 200, 40, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 175
};
int i = 1; //-snip-
bool blink=true;

void setup()
{
	// initialize the digital pin as an output.
	pinMode(0, OUTPUT); //LED on Model B
	pinMode(1, OUTPUT); //LED on Model A
	DigiKeyboard.delay(2000); //wait 2000 milliseconds before first run, to give target time to initialize
}

void loop()
{

	//should code be runned in this loop?
	if (i != 0) {
		DigiKeyboard.sendKeyStroke(0);

		//parse raw duckencoder script
		for (int i=0; i<DUCK_LEN; i+=2)
		{
			uint8_t key = pgm_read_word_near(duckraw + i);
			uint8_t mod = pgm_read_word_near(duckraw + i+1);
			if (key == 0) //delay (a delay>255 is split into a sequence of delays)
			{
				DigiKeyboard.delay(mod);
			}
			else DigiKeyboard.sendKeyStroke(key,mod);
		}
		i--;
		DigiKeyboard.delay(5000); //wait 5000 milliseconds before next loop iteration

	}
	else if (blink)
	{
		digitalWrite(0, HIGH);   // turn the LED on (HIGH is the voltage level)
		digitalWrite(1, HIGH);
		delay(100);               // wait for a second
		digitalWrite(0, LOW);    // turn the LED off by making the voltage LOW
		digitalWrite(1, LOW);
		delay(100);               // wait for a second
	}
}
